export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto max-w-3xl py-16 md:py-24 px-4">
      <div className="prose dark:prose-invert lg:prose-lg">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <p>
          Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the UGTechsolution website (the "Service") operated by UGTechsolution ("us", "we", or "our"). Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Services</h2>
        <p>
          UGTechsolution provides e-commerce development services for SMEs and technical SEO services for startups. We also offer an AI-powered Content Idea Generator tool. All services are provided as described on our website and are subject to the specific terms outlined in your service agreement with us.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">2. AI Content Generator</h2>
        <p>
          The AI Content Idea Generator is provided as a tool to assist with content creation. You are responsible for the content you generate and how you use it. The generated content is not guaranteed to be unique, accurate, or complete. You agree to use the tool in compliance with all applicable laws and not to generate harmful, illegal, or infringing content. We are not liable for any claims or damages arising from your use of the generated content.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Intellectual Property</h2>
        <p>
          The Service and its original content (excluding content provided by users or generated by the AI tool at your request), features, and functionality are and will remain the exclusive property of UGTechsolution and its licensors.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">4. Limitation of Liability</h2>
        <p>
          In no event shall UGTechsolution, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of Uganda, without regard to its conflict of law provisions.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">6. Changes</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us through our <a href="/contact" className="text-primary hover:underline">contact page</a>.
        </p>
      </div>
    </div>
  );
}
